# Streamlit Secrets Configuration
# Copy this file to .streamlit/secrets.toml and add your HuggingFace token

# HuggingFace Token for model access
# Get your token from: https://huggingface.co/settings/tokens
HUGGINGFACE_TOKEN = "your_huggingface_token_here"

# Optional: Additional configuration
# MODEL_CACHE_DIR = "/tmp/models"
# MAX_MEMORY_USAGE = "2GB" 